<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA2X89Nx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA2X89Nx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA2X89Nx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA2X89Nx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerA2X89Nx\App_KernelDevDebugContainer([
    'container.build_hash' => 'A2X89Nx',
    'container.build_id' => '7739b3d5',
    'container.build_time' => 1776397681,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA2X89Nx');
